switch to debian in the docker demo
archlinux fails to install packages half the time

  error: key "Christian Hesse (Arch Linux Package Signing) <arch@eworm.de>" could not be imported

This seems to be a long-standing bug in arch that hasn't been acknowledged.
Users suffering from it are offered to to repeatedly wipe their keyring,
reinitialize, and retry.